### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by SzymonPuszcz** [MPrzekop/Muzykando-BE#2]
Guys, can we deploy it to production? It's such a great shop. We'll be rich. 

![image](https://user-images.githubusercontent.com/27854440/96788171-52ad4580-13f3-11eb-9ede-3ffb3004edd4.png)

**Comment by rzeckiporzecki** [comment]
Szymon, wypadek był 3 lata temu, to nie Twoja wina, you have to let us go

**Comment by rzeckiporzecki** [comment]
poza tym produkty proponowane nie działają
